language: node_js
sudo: false
node_js:
- '4'
- '6'
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: hoWc3Cm8qrCl3QVrhibKNTnyEX2m8OFf/rs0xdZ/+gVWaE0fRd81/CmMzqOC/kCkZ6LJ/zST836k/opufq9m5o88rwIQvv0gzUfpuOdElgLOoEgXcSgPpPfZcA0Cw0Nc6c3jJeXaM76HLEpNXwfPMeadMrUrRKd0M0SzwK2MWAntXSs1GUobuGsaDRu08m4moWuY0zIgV/tRj/P+Fx/odPs4RXddvzrE9ZQxGr0Pl/FZ0jLGSEG1CGJa4HAuAMjTVCVrg55BpHDqAM+YsztneL9teEBImmy/mziG3hVSHpJPlo7cW8V6Ms0YDMvlrAK7tj8p9p5gQgalYubAryAbRDK+vNeWBERav1RKaDtFHEUnWdIbBCe+Galr2KOgX0rjQgpLEWzl4lSirsSe95OeofWhliovEA2Wf75+9iW5oDJqxWSZK1Z+EqQUZ0xYxUWbHEYbgx+Hj1GUos5q3nT/8DsKlwmxkmMuBndUW1JVMTI1JxEI4tK2adCkZ4bbMxiHp7R8k+YdfT+gKNqjX0SIwXZa8gEH7IizEUq4X4KqjFMpOXS6fQ/5opjiPt+s1xou/J1jFN+IQQoSXHYPWb4I0clybQlkSAkXfwkvcyPH/IEUZjttVnI1jgXZd3SiiMDSi/CLxM3oREmFNIyXANe2y9Pvjb1wqJsEIABnhhegE14=
  - secure: rans760qMYJIEWiFPdHUIOb6fOU519vI0SKYaydoJHCdCVF6VIIGcFoJ6WD0xjztBuh3pi3EQDvxbDqwt4z2+6DIef7HBmch0kTRHEaKF1q/axlLTLngeBg23C+zPqZEbH6LS3uX4uvmhXBh3vH1hhUH/OC1FsHWrL0PLEj//9hFYppO9Rr10WgejGnDLONYnf4PxMMHo9FJDw8RTVrLJtScAt5bLoVAGsV2SwtjWXlojaHFnmsiubtt3bcUysh4pj3MpKibqFFC5RJcy/d/bvC0hCEb18O9m7ghy1yrXRBTSeK2dL4NIevmd/BfcUqw2Zn+ofWoDD2KVaVCmcWwJGjxiXc8A0Ve5ZhfLYz0XQHJF6AYCdQyDaoHKIFW5isBoiisIzhGjrU7IMzNlx7TRC0GfmskBoYcK7SoeHXK4zqtHkLjueRr4yETQh6jHdPvEGfJWPwZz8aPKbSh6n90yuP4bTtgr7tzZlxvdM1ghlT/v1fwpjNRj+jvyzfr2AoyLr3kerzFogwaVnzs4yO+gWkvVJzr+NWF8Ksyc84iJkgvADU/BHh0MEeZRFqxtFtbp1D5s84dBReXtlRxRg1vCptkrxC3JLz6JFmClvRoo4LN9qYNfwcRp+RutpEnaIA/CC3E5zd/cgiGBiRV3Im17Epnmms3hhfXhW4/BfUyYsc=
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: SX0Po3nXjNrHKCPLCqqm6BsCKguVJ8wHugvRfEkviOJRj7N+NLeyskmX9WIlOvd95Gzjf1Dt1sSeMpnJhU/HFMJInLC3sfpIdCFnVoRe49jk3LXga5EKs3miainGEcGEzu1EkSa7aSp+G0XoQQSAKANZJuomftS5HhQDV4tJBo7TO4Aja875D2+52ZIMAHT1vUUWAyueV02njeTH8c9UC4zSTzN3DkdouTusL2Tri0TMuoeAabCNMgraG4bct2wF85qNDRhlvb6vH1LawLxLZQUnElhi4kg4NacoJotU4ireQomnmD0pjcC8gl9kZyzexGo2CfIq/fKDhlFi3LEaJGQarRFl235pr+L7b/CNsbVoaiK6EfBzKr1E3RWu+vaecCr7LObxQ+OFFIiQM89UpU7B3bcy2xzhefe8/CAwe51IuZtFyWDqp1l6lTQnjkqirN0fmdX/exAQHv9iAtMa26UF0k19Ml/KQIkSSm2+UXKIEu3htarBAQg1G2sM2AglQ4zklQbOs3BlhV47ttmGB4fHJtBGSw3DBX/Y/74n5Hnz9wvqak7EyKqvvLf+2yAIc0lQyEL0VoBy8d+uYxissJnQulAuN5JY9G4p7XlNJBs1LmDFLSGWswa285l+1a9ZvKjGNOQidiWTgGaDL8kPLaV/80Bd7vKt7cOe0ffweXM=
  on:
    tags: true
    repo: taskcluster/azure-blob-storage
